### ISSUE TITLE
(Video) Resize Window

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/raylib-libretro#7]
Allow resizing the window and fit the Texture to fit within.

**Comment by raysan5** [comment]
@RobLoach I imagine you used [core_window_letterbox](https://github.com/raysan5/raylib/blob/master/examples/core/core_window_letterbox.c) implementation for this one!

**Comment by RobLoach** [comment]
@raysan5 The implementation looks pretty similar!
https://github.com/RobLoach/raylib-libretro/blob/master/include/rlibretro.h#L656-L674
